services:
  mysql:
    image: mysql:8.0
    container_name: curso_mysql
    environment:
      MYSQL_DATABASE: docker_db
      MYSQL_USER: docker_usr
      MYSQL_PASSWORD: docker_pwd
      MYSQL_ROOT_PASSWORD: root_pwd
    ports:
      - "3306:3306"
